-- =============================================================
-- Echoes of Legend - migration 15
-- RESET THE CURRENT DAILY PUZZLE
-- -------------------------------------------------------------
-- Paste into: Dashboard -> SQL Editor -> New query -> Run.
-- Safe to run more than once. Requires migration 04 (and 07/10).
--
-- WHY THIS EXISTS
--
--   The puzzle forge was rewritten on 2026-08-16 to certify a 3-5
--   round solution (see docs/DESIGN-Daily-Puzzle.md). Any position
--   already sitting in `daily_puzzles` was generated by the old
--   engine, which optimised only for "the AI wins within twenty
--   rounds". Those boards ship no `solveBy`, so the client derives
--   a five-round deadline for them - and the old forge never proved
--   they can be won in five rounds. A stale position is therefore
--   not merely long, it may be UNSOLVABLE under the new limit.
--
--   Deploying the rewrite means clearing the board it replaces.
--   Before this migration the only way to do that was to hand-delete
--   rows across three tables in the right order, which is exactly
--   the "jsonb spelunking trip" the workbench doc calls out as the
--   wrong answer.
--
-- WHAT A RESET DOES
--
--   1. Deletes the active and staged positions for the service day.
--      `daily_puzzle_attempts` has ON DELETE CASCADE, so every
--      player's consumed attempt for that board disappears with it.
--      THIS IS THE POINT: a player who already burned both attempts
--      on the stale board would otherwise be locked out until the
--      next reset through no fault of their own.
--   2. Deletes any generation lease for the day, so a browser can
--      immediately win a new one instead of waiting up to three
--      minutes for a stale lease to expire.
--
--   It does NOT generate the replacement. Generation is browser
--   work by design (migration 04): the next signed-in client to
--   open the Daily card finds no current row, takes the recovery
--   lease and forges a new position with the new engine. Reset,
--   then open the game.
--
-- WHY service_role ONLY
--
--   Wiping the shared board is not a player action. `claim_daily_*`
--   is granted to `authenticated` because those RPCs only ever touch
--   the caller's own rows; this one deletes everyone's. It is
--   granted to `service_role`, which means the SQL Editor and a
--   trusted backend, and nothing that ships in the browser bundle.
-- =============================================================

create or replace function public.reset_daily_puzzle(p_day date default null)
returns table (
  cleared_day date,
  positions_removed integer,
  attempts_removed integer,
  leases_removed integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  local_now timestamp := timezone('America/New_York', now());
  target_day date;
  n_pos integer := 0;
  n_att integer := 0;
  n_job integer := 0;
begin
  -- The same advisory lock the publish and generate paths take, so a
  -- reset can never interleave with a browser submitting a candidate
  -- and leave a half-cleared day behind.
  perform pg_advisory_xact_lock(hashtext('eol.daily-puzzle.publish'));
  perform pg_advisory_xact_lock(hashtext('eol.daily-puzzle.generate'));

  -- The SERVICE DAY, not the calendar day. The puzzle rolls at 7:00 AM
  -- Eastern, so before 7 AM "today's puzzle" is still yesterday's date -
  -- the same arithmetic every other RPC in migration 04 uses. Getting
  -- this wrong at 6:30 AM would clear tomorrow's staged position and
  -- leave the board the owner actually wanted gone still live.
  target_day := coalesce(
    p_day,
    local_now::date - case when extract(hour from local_now)::integer < 7 then 1 else 0 end
  );

  -- Counted BEFORE the delete: attempts vanish by cascade, so after the
  -- position is gone there is nothing left to count and the report would
  -- always say zero.
  select count(*) into n_att
    from public.daily_puzzle_attempts a
    join public.daily_puzzles p on p.id = a.puzzle_id
   where p.puzzle_day = target_day;

  delete from public.daily_puzzles where puzzle_day = target_day;
  get diagnostics n_pos = row_count;

  delete from public.daily_puzzle_jobs where puzzle_day = target_day;
  get diagnostics n_job = row_count;

  return query select target_day, n_pos, n_att, n_job;
end;
$$;

revoke all on function public.reset_daily_puzzle(date) from public, anon, authenticated;
grant execute on function public.reset_daily_puzzle(date) to service_role;


-- =============================================================
-- HOW TO RESET TODAY'S PUZZLE
-- -------------------------------------------------------------
-- Run this one line in the SQL Editor:
--
--     select * from public.reset_daily_puzzle();
--
-- It reports what it removed, for example:
--
--     cleared_day | positions_removed | attempts_removed | leases_removed
--     2026-08-16  |                 1 |                3 |              0
--
-- Then open the game while signed in. The Daily card will show
-- "Puzzle under construction" for roughly half a minute while a
-- browser forges the replacement, and the new board will carry a
-- certified 3-5 round solution.
--
-- To clear a specific day instead of the current one:
--
--     select * from public.reset_daily_puzzle('2026-08-17');
--
-- (Useful for dropping a STAGED position that was forged by the old
-- engine before tomorrow's 7:00 AM publish promotes it.)
-- =============================================================
