-- =============================================================
-- Echoes of Legend - migration 06
-- PRIVACY-LIGHT MEASUREMENT + PLAYER FEEDBACK
-- -------------------------------------------------------------
-- Paste into: Dashboard -> SQL Editor -> New query -> Run.
-- Safe to run more than once.
--
-- Storage is deliberately narrow:
--   telemetry_events  anonymous funnel events, retained for 180 days
--   player_feedback   messages players deliberately submit
--
-- Browser clients receive NO direct table access. They may only call
-- the two validating, rate-limited RPCs below. The owner reads the rows
-- from the Supabase dashboard or the queries in docs/MEASUREMENT.md.
-- =============================================================

begin;

create table if not exists public.telemetry_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id uuid not null,
  session_id uuid not null,
  event_name text not null check (event_name in (
    'session_started',
    'view_opened',
    'mode_selected',
    'account_ready',
    'multiplayer_queue_started',
    'multiplayer_match_found',
    'battle_started',
    'battle_completed',
    'daily_opened',
    'feedback_opened',
    'client_error'
  )),
  context jsonb not null default '{}'::jsonb
);

create index if not exists telemetry_events_created_idx
  on public.telemetry_events(created_at desc);
create index if not exists telemetry_events_visitor_created_idx
  on public.telemetry_events(visitor_id, created_at desc);
create index if not exists telemetry_events_name_created_idx
  on public.telemetry_events(event_name, created_at desc);

create table if not exists public.player_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id uuid not null,
  session_id uuid not null,
  category text not null check (category in ('bug', 'balance', 'confusing', 'suggestion', 'other')),
  message text not null check (char_length(message) between 3 and 2000),
  context jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new', 'reviewed', 'resolved')),
  owner_note text
);

create index if not exists player_feedback_created_idx
  on public.player_feedback(created_at desc);
create index if not exists player_feedback_status_created_idx
  on public.player_feedback(status, created_at desc);
create index if not exists player_feedback_visitor_created_idx
  on public.player_feedback(visitor_id, created_at desc);

alter table public.telemetry_events enable row level security;
alter table public.player_feedback enable row level security;

-- Dashboard owners and service-role tools can inspect the tables. Browser
-- roles cannot select, insert, update or delete rows directly.
revoke all on table public.telemetry_events from public, anon, authenticated;
revoke all on table public.player_feedback from public, anon, authenticated;

-- =============================================================
-- record_telemetry
-- An anonymous visitor id is generated and stored by the browser. It is
-- not an email, callsign, account id or advertising id. Telemetry remains
-- anonymous even when the player is signed in. At most 120 events per
-- visitor per hour are accepted.
-- =============================================================
create or replace function public.record_telemetry(
  p_visitor uuid,
  p_session uuid,
  p_event text,
  p_context jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count integer;
  clean_context jsonb := coalesce(p_context, '{}'::jsonb);
begin
  if p_visitor is null or p_session is null then
    raise exception 'measurement identifier required' using errcode = '22023';
  end if;

  if p_event is null or p_event not in (
    'session_started',
    'view_opened',
    'mode_selected',
    'account_ready',
    'multiplayer_queue_started',
    'multiplayer_match_found',
    'battle_started',
    'battle_completed',
    'daily_opened',
    'feedback_opened',
    'client_error'
  ) then
    raise exception 'unsupported measurement event' using errcode = '22023';
  end if;

  if jsonb_typeof(clean_context) <> 'object' then
    raise exception 'measurement context must be an object' using errcode = '22023';
  end if;
  if octet_length(clean_context::text) > 4096 then
    raise exception 'measurement context is too large' using errcode = '22023';
  end if;

  select count(*)::integer into recent_count
    from public.telemetry_events e
   where e.visitor_id = p_visitor
     and e.created_at > now() - interval '1 hour';
  if recent_count >= 120 then
    return;
  end if;

  insert into public.telemetry_events(
    visitor_id,
    session_id,
    event_name,
    context
  ) values (
    p_visitor,
    p_session,
    p_event,
    clean_context
  );

  -- Tiny probabilistic housekeeping keeps raw events bounded without a
  -- cron job or external worker. The created_at index makes this cheap.
  if random() < 0.01 then
    delete from public.telemetry_events
     where created_at < now() - interval '180 days';
  end if;
end;
$$;

revoke all on function public.record_telemetry(uuid, uuid, text, jsonb) from public;
grant execute on function public.record_telemetry(uuid, uuid, text, jsonb) to anon, authenticated;

-- =============================================================
-- submit_player_feedback
-- Feedback is voluntary and may include a small diagnostics object the
-- player can turn off in the form. At most five submissions per visitor
-- per day are accepted. Messages remain until the owner resolves/deletes
-- them; they are not part of the 180-day telemetry cleanup.
-- =============================================================
create or replace function public.submit_player_feedback(
  p_visitor uuid,
  p_session uuid,
  p_category text,
  p_message text,
  p_context jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count integer;
  clean_message text := btrim(coalesce(p_message, ''));
  clean_context jsonb := coalesce(p_context, '{}'::jsonb);
  new_id bigint;
begin
  if p_visitor is null or p_session is null then
    raise exception 'feedback identifier required' using errcode = '22023';
  end if;
  if p_category is null or p_category not in ('bug', 'balance', 'confusing', 'suggestion', 'other') then
    raise exception 'unsupported feedback category' using errcode = '22023';
  end if;
  if char_length(clean_message) < 3 or char_length(clean_message) > 2000 then
    raise exception 'feedback must be between 3 and 2000 characters' using errcode = '22023';
  end if;
  if jsonb_typeof(clean_context) <> 'object' then
    raise exception 'feedback context must be an object' using errcode = '22023';
  end if;
  if octet_length(clean_context::text) > 8192 then
    raise exception 'feedback context is too large' using errcode = '22023';
  end if;

  select count(*)::integer into recent_count
    from public.player_feedback f
   where f.visitor_id = p_visitor
     and f.created_at > now() - interval '1 day';
  if recent_count >= 5 then
    raise exception 'feedback limit reached; try again tomorrow' using errcode = '54000';
  end if;

  insert into public.player_feedback(
    visitor_id,
    session_id,
    category,
    message,
    context
  ) values (
    p_visitor,
    p_session,
    p_category,
    clean_message,
    clean_context
  ) returning id into new_id;

  return new_id;
end;
$$;

revoke all on function public.submit_player_feedback(uuid, uuid, text, text, jsonb) from public;
grant execute on function public.submit_player_feedback(uuid, uuid, text, text, jsonb) to anon, authenticated;

commit;
